### ISSUE TITLE
 AttributeError: 'Scenario' object has no attribute 'find_lanelet_by_position'

### ISSUE THREAD

**Issue by ZhaiMen-Hub** [CommonRoad/commonroad-reactive-planner#2]
An AttributeError occurs when launching `python run_planner.py`

The error message is as follows

```bash
  (commonroadPyPi) ➜  commonroad-reactive-planner git:(master) python run_planner.py
  Traceback (most recent call last):
    File "run_planner.py", line 43, in <module>
      route_planner = RoutePlanner(config.scenario, config.planning_problem)
    File "/home/robotics/miniconda3/envs/commonroadPyPi/lib/python3.8/site-packages/commonroad_route_planner/route_planner.py", line 92, in __init__
      self._init_lanelet_ids_for_start_and_overtake()
    File "/home/robotics/miniconda3/envs/commonroadPyPi/lib/python3.8/site-packages/commonroad_route_planner/route_planner.py", line 260, in _init_lanelet_ids_for_start_and_overtake
      self._lanelet_network.find_lanelet_by_position([initial_state.position])[0]
  AttributeError: 'Scenario' object has no attribute 'find_lanelet_by_position'

**Comment by ZhaiMen-Hub** [comment]
It seems that the reason is the version of commonroad-route-planner is too high. 

The requirement.txt only required >=2024.1.1, hence pip will install the 2024.2.0 version (i.e. the newest version). 
Running `pip install commonroad-route-planner==2024.1.1` can solve this problem.

**Comment by lihu2022** [comment]
hey,bro.Thank you for providing this debug method, but i am little interesting that how do you know this bug you mentioned is version mistake.I try lot of method but not success to solve this bug.
